"""empty message

Revision ID: 0102e2942680
Revises: c4db5ae9e1b8
Create Date: 2021-11-14 16:54:03.342161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0102e2942680'
down_revision = 'c4db5ae9e1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_join_song_id_fkey', 'playlist_join', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_join', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlist_join', type_='foreignkey')
    op.create_foreign_key('playlist_join_song_id_fkey', 'playlist_join', 'songs', ['song_id'], ['id'])
    # ### end Alembic commands ###
