"""empty message

Revision ID: dbb0d215a412
Revises: 9aa98bcc4125
Create Date: 2021-11-08 17:17:46.671584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb0d215a412'
down_revision = '9aa98bcc4125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('song', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'song')
    # ### end Alembic commands ###
