"""empty message

Revision ID: 9aa98bcc4125
Revises: 6dcf1779bb40
Create Date: 2021-11-08 16:39:12.128120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa98bcc4125'
down_revision = '6dcf1779bb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_url', sa.String(length=255), nullable=True))
    op.add_column('songs', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'image_url')
    op.drop_column('songs', 'song_url')
    # ### end Alembic commands ###
