"""empty message

Revision ID: 7a5b09eed86f
Revises: 0102e2942680
Create Date: 2021-12-16 16:53:44.493760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5b09eed86f'
down_revision = '0102e2942680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'index')
    # ### end Alembic commands ###
