"""empty message

Revision ID: 82e036661cb2
Revises: 3e630beaf116
Create Date: 2021-11-13 21:31:13.715612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e036661cb2'
down_revision = '3e630beaf116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_join', sa.Column('id', sa.Integer(),
               nullable=False, autoincrement=True, primary_key=True)),
    op.alter_column('playlist_join', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playlist_join', 'playlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlist_join', 'playlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playlist_join', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('playlist_join', 'id')
    # ### end Alembic commands ###
